---
version: "3"
services:
 devopsdb:
   image: nikhilkaraggi/docker:dbimg
   ports:
     - "3306:3306"
   deploy:
     replicas: 3

 application:
   image: nikhilkaraggi/docker:appimg
   ports:
     - "1111:8080"
   deploy:
     replicas: 3
   depends_on:
     - "devopsdb"
